# Data Wrangling Notebook

#### Overall Goal: Build node/adjacency matrix features and info (PyTorch Geometric or Spektral suggested)

### 1. Members Graph

- **Nodes**: member_ids from member-edges 

- **Node Attributes**: hometown, city, state, lat, lon from meta-members; event_id, group_id from rsvps; weight from member-to-group-edges (number of shared groups between members)

- **Edges**: connections between members

- **Edge Attributes**: weight from member-edges  (what is weight here? how many events + grps they share? how calculated?)

- **Note**: not a digraph

### 2. Groups Graph

- **Nodes**: group_id from meta-groups 

- **Node Attributes**: : group_name, num_members, category_id, category_name, organizer_id, group_urlname from meta-groups

- **Edges**: connections between members

- **Edge Attributes**: weight from group-edges (number of shared members between groups)

- **Note**: also not a digraph

### Imports

In [60]:
# General libraries
import pandas as pd
import numpy as np

# Graphing libraries
import networkx as nx
import torch
from torch_geometric.utils.convert import from_networkx
from torch_geometric.data import Data

In [ ]:
%%capture

%run data.ipynb

In [29]:
# Example

# PyG has a function to convert nx graphs into Data objects 
data = from_networkx(G_sample, group_node_attrs='')
print(data.x)
print(data.edge_index)

tensor([[0.0133],
        [0.0000],
        [0.0000],
        ...,
        [0.0000],
        [0.0000],
        [0.0000]])
tensor([[   0,    0,    0,  ..., 3838, 3839, 3840],
        [   1,    2,    3,  ..., 3507, 3507, 3507]])

### Building Graph 1: Members

In [37]:
# Drop member 239124265, as no metadata exits for it (confirmed in debugging not shown)
subset = subset[(subset['member1'] != 239124265) & (subset['member2'] != 239124265)]

mem_edges = mem_edges[(mem_edges['member1'] != 239124265) & (mem_edges['member2'] != 239124265)]

In [54]:
# Create dictionary of dictionaries
mem_dict = mem_df.to_dict(orient='index')

In [55]:
mem_df

                 hometown       city state    lat    lon
member_id
2069            Brentwood  Brentwood    TN  36.00 -86.79
8386            Nashville  Nashville    TN  36.07 -86.78
9205            Brentwood  Brentwood    TN  36.00 -86.79
17903        Not provided  Nashville    TN  36.13 -86.80
20418      Huntington, WV  Nashville    TN  36.17 -86.72
...                   ...        ...   ...    ...    ...
239513469    Not provided  Nashville    TN  36.09 -86.82
239515413    Not provided  La Vergne    TN  36.00 -86.57
239519977    Not provided  Nashville    TN  36.17 -86.78
239520184    Not provided  Nashville    TN  36.14 -86.74
239558741    Not provided  Brentwood    TN  36.00 -86.79

[24591 rows x 5 columns]

In [56]:
# Build graph from subset for now
G_m = nx.from_pandas_edgelist(
    subset,
    source='member1',
    target='member2',
    edge_attr='weight',
    create_using=nx.Graph())
# Set attributes 
nx.set_node_attributes(G_m, mem_dict)

In [57]:
print(nx.get_node_attributes(G_m, 'hometown'))

{198737924: 'Not provided', 220654721: 'Not provided', 208201738: 'Not provided', 88664332: 'Nashville', 8640526: 'Not provided', 56356372: 'Lewisburg', 183880473: 'Not provided', 194617630: 'Not provided', 185626278: 'Gainesville, FL', 8809394: 'Austin', 193825984: 'Not provided', 145838912: 'New York', 182472899: 'Springfield ', 8998727: 'Not provided', 3036107: 'Not provided', 127853262: 'Hermitage, TN', 209148366: 'Not provided', 207093714: 'Not provided', 204969170: 'Not provided', 156443612: 'Not provided', 12916961: 'Not provided', 66842212: 'Nashville', 216446825: 'Not provided', 183097071: 'Not provided', 212660721: 'Not provided', 160810612: 'Nashville', 200806774: 'Not provided', 154764282: 'Not provided', 14497407: 'Chicago', 73498632: 'Not provided', 66999812: 'Nashville', 221126666: 'Not provided', 197747724: 'Not provided', 91563022: 'Indianapolis, IN', 10798095: 'Savannah', 201765390: 'Not provided', 204465678: 'Not provided', 207654954: 'Not provided', 188889135: 'Not provided', 53159472: 'Not provided', 192814642: 'Not provided', 197681727: 'Not provided', 189163080: 'Not provided', 223143499: 'Howard', 141761102: 'Not provided', 26324562: 'Not provided', 216567379: 'Not provided', 202135638: 'Not provided', 150355032: 'Not provided', 212232797: 'Not provided', 117939302: 'Not provided', 211518566: 'Not provided', 230659176: 'Not provided', 26285162: 'Not provided', 222579306: 'Not provided', 45382252: 'Not provided', 183766136: 'Not provided', 192131215: 'Not provided', 189705878: 'Not provided', 185636517: 'Not provided', 109335722: 'Not provided', 184418986: 'Not provided', 144256692: 'Not provided', 220919480: 'Not provided', 42441402: 'Not provided', 238843578: 'Not provided', 183370428: 'MADISON', 13579455: 'Not provided', 35275462: 'Not provided', 205336779: 'Not provided', 184175830: 'Not provided', 218384086: 'Not provided', 198681310: 'Not provided', 151512802: 'Not provided', 195517167: 'Not provided', 182863105: 'Katy', 213190404: 'Not provided', 14144267: 'Not provided', 238077203: 'Not provided', 221803801: 'Not provided', 235847459: 'Not provided', 56588072: 'Not provided', 44125492: 'Not provided', 127366452: 'Not provided', 80835382: 'Not provided', 26301242: 'Not provided', 222674749: 'Not provided', 200374078: 'Not provided', 221257542: 'Not provided', 174868302: 'Not provided', 27567952: 'Memphis, TN', 217355604: 'Not provided', 205202788: 'Not provided', 183871346: 'Grand Island', 41081212: 'Not provided', 128034692: 'Not provided', 220757388: 'Not provided', 231170959: 'Not provided', 144318352: 'Not provided', 44449682: 'Not provided', 192589715: 'Not provided', 233770901: 'Not provided', 49891742: 'Not provided', 198331815: 'Not provided', 212544424: 'Not provided', 186565546: 'Not provided', 209759658: 'Not provided', 206603702: 'Not provided', 189139900: 'Not provided', 183439318: 'Not provided', 192826336: 'Dallas, TX', 198802912: 'Not provided', 225017316: 'Not provided', 148361702: 'Not provided', 32520682: 'Not provided', 215422451: 'Not provided', 229446139: 'Not provided', 234360831: 'Not provided', 182943766: 'Not provided', 4278530: 'Not provided', 228303620: 'Not provided', 215245573: 'Not provided', 223617033: 'Not provided', 217510929: 'Not provided', 7305493: 'Not provided', 32809502: 'Not provided', 215170597: 'Not provided', 227210790: 'Not provided', 225501228: 'Not provided', 223055408: 'Not provided', 229498167: 'Not provided', 211597628: 'Not provided', 184991548: 'Not provided', 150449212: 'Nashville', 215552322: 'Not provided', 223293250: 'Not provided', 211057221: 'Not provided', 150902602: 'Not provided', 186374987: 'Not provided', 77062222: 'Nashville, TN', 226704978: 'Not provided', 178169942: 'Not provided', 203468630: 'Not provided', 234205531: 'Not provided', 11205213: 'Mount Juliet', 193777510: 'Not provided', 7377000: 'Not provided', 2807913: 'Tulsa, OK', 9561451: 'Franklin, TN', 223389804: 'Not provided', 30687102: 'London, England', 208813186: 'Nashville, TN', 108297612: 'Nashville, TN', 186008461: 'Nashville', 203857825: 'Not provided', 125908132: 'Not provided', 130333862: 'Not provided', 216144561: 'Not provided', 12650422: 'Not provided', 147275192: 'Not provided', 196470471: 'Nashville', 223530441: 'Not provided', 34585292: 'New York, NY', 218877394: 'Not provided', 226052576: 'Not provided', 214683367: 'Not provided', 207274472: 'Not provided', 183109097: 'Warren, OH', 9167857: 'Kansas City', 156342002: 'Not provided', 63998462: 'Nashville', 216072216: 'Not provided', 8731661: 'Durham, NC', 10865691: 'Brentwood, TN', 79171612: 'Not provided', 222840882: 'Not provided', 223455283: 'Not provided', 229310518: 'Not provided', 63041592: 'Nashville', 223251513: 'Not provided', 186020922: 'Not provided', 12625982: 'Nashville', 95921222: 'Not provided', 232312915: 'Not provided', 208138348: 'Not provided', 187055230: 'Not provided', 227711104: 'Not provided', 215792772: 'Not provided', 215840904: 'Not provided', 215792789: 'Not provided', 215312542: 'Not provided', 230674601: 'Not provided', 217309361: 'Not provided', 202115252: 'Not provided', 216357048: 'Not provided', 8486078: 'Not provided', 231257288: 'Not provided', 225614029: 'Not provided', 220540112: 'Franklin', 233063638: 'Not provided', 218552556: 'Not provided', 4801776: 'Not provided', 178090242: 'Not provided', 199174403: 'Not provided', 235883779: 'Not provided', 194440461: 'Not provided', 96331022: 'Not provided', 232828173: 'Not provided', 225229086: 'Not provided', 207061281: 'Not provided', 219866401: 'Not provided', 222925100: 'Not provided', 183794995: 'Not provided', 202429748: 'Not provided', 210195771: 'Not provided', 215789888: 'Nashville', 188816707: 'Not provided', 218506563: 'Not provided', 220774730: 'Not provided', 233000275: 'Not provided', 161200492: 'Not provided', 8218996: 'Indianapolis, Indiana', 5900662: 'Nashville, TN', 39926142: 'Not provided', 219183495: 'Not provided', 120856972: 'Not provided', 215431567: 'Not provided', 220686748: 'Not provided', 183447968: 'Not provided', 93820322: 'Not provided', 207538596: 'Chicago', 219316647: 'Not provided', 229173683: 'Not provided', 202855865: 'Not provided', 210471371: 'Not provided', 186005970: 'Nashville', 116617692: 'Denver', 223324639: 'Not provided', 173042152: 'Not provided', 217907689: 'Not provided', 167335402: 'Not provided', 12626414: 'Not provided', 13717998: 'Not provided', 4994544: 'Not provided', 126998022: 'Not provided', 192465426: 'Not provided', 198734366: 'Not provided', 137768482: 'Not provided', 221958694: 'Nashville', 225287724: 'Nashville', 218242614: 'Not provided', 225611321: 'Not provided', 207608384: 'Not provided', 222846545: 'Not provided', 233015894: 'Not provided', 4193895: 'Nashville', 18382441: 'Nashville', 227378801: 'Not provided', 215791226: 'Not provided', 219320959: 'Not provided', 192140941: 'Not provided', 217856665: 'Not provided', 215956136: 'Not provided', 219312808: 'Not provided', 160338602: 'Nashville, TN', 227287722: 'Not provided', 149979832: 'Not provided', 216187595: 'Not provided', 11872972: 'Not provided', 218572495: 'Not provided', 28278482: 'Not provided', 16190171: 'Miami, FL', 206806749: 'Not provided', 206598883: 'Not provided', 221165289: 'Not provided', 178938602: 'Not provided', 223044356: 'Not provided', 220962574: 'Not provided', 227444521: 'Not provided', 208117552: 'Not provided', 185915186: 'Not provided', 232732487: 'Not provided', 190427976: 'Not provided', 6045513: 'Not provided', 14638921: 'Not provided', 214401868: 'Nashville', 185689933: 'Not provided', 225525590: 'Not provided', 215793495: 'Baltimore, MD', 215872355: 'Not provided', 218146687: 'Not provided', 193615746: 'Not provided', 218505095: 'Not provided', 194381707: 'Nashville', 9902996: 'Not provided', 71482262: 'Not provided', 219309975: 'Not provided', 219875228: 'Not provided', 220548003: 'Not provided', 217752488: 'Not provided', 9652156: 'Not provided', 225500093: 'Not provided', 215792581: 'Not provided', 83770322: 'Nashville', 32768992: 'Not provided', 215899104: 'Not provided', 223419366: 'Not provided', 226043889: 'Not provided', 211941374: 'Not provided', 183566364: 'Ashland City, TN', 36431872: 'Not provided', 102000142: 'hermitage', 205622291: 'Mcminnville', 2310683: 'Nashville', 185266203: 'Not provided', 184040997: 'Not provided', 6298662: 'Greeneville, TN', 201022505: 'Not provided', 58539562: 'Nashville, TN', 7398966: 'Not provided', 35429432: 'Hayward', 206361658: 'Not provided', 8744513: 'Nolensville', 202164803: 'Not provided', 143924292: 'Not provided', 13849159: 'Not provided', 12250724: 'Not provided', 56561772: 'Not provided', 10184307: 'Middle Tennessee', 189584508: 'Not provided', 11771032: 'USA', 200418463: 'Not provided', 198025377: 'Not provided', 34983592: 'Smyrna', 183268010: 'Not provided', 4612278: 'Not provided', 5861048: 'Not provided', 13832894: 'Not provided', 174732482: 'Not provided', 9020102: 'Not provided', 6642893: 'Not provided', 197691599: 'Not provided', 39322832: 'Not provided', 12771542: 'Not provided', 55746782: 'Brentwood', 174031072: 'Not provided', 122881762: 'Not provided', 8898275: 'Not provided', 208628458: 'Not provided', 62010092: 'Not provided', 5985520: 'Not provided', 64978672: 'Not provided', 9918706: 'Columbia, TN', 120291572: 'Not provided', 69346552: 'Not provided', 204714239: 'Not provided', 14643466: 'Not provided', 38039822: 'Not provided', 217563923: 'Not provided', 184714020: 'Not provided', 195299122: 'Not provided', 33162042: 'Clarksville', 125708602: 'Not provided', 5459777: 'Not provided', 30673232: 'Not provided', 33721682: 'Not provided', 3634004: 'Frankfort', 110855512: 'Not provided', 84790622: 'Not provided', 197581156: 'Not provided', 132266342: 'Not provided', 206448496: 'Not provided', 69179782: 'Not provided', 6932365: 'Nashville', 199029649: 'Not provided', 38942102: 'Not provided', 2170271: 'Not provided', 39391662: 'Not provided', 185792430: 'Not provided', 183844788: 'Not provided', 112420792: 'Franklin', 206572986: 'Not provided', 4560828: 'Not provided', 48454082: 'Not provided', 13684166: 'Not provided', 14334918: 'Not provided', 84206032: 'Franklin, IN', 211432916: 'Not provided', 12974037: 'Louisville', 155278822: 'Memphis', 187508199: 'Not provided', 212431847: 'Not provided', 33639402: 'Nashville', 60494832: 'Franklin', 78526962: 'Not provided', 8794617: 'Nashville', 172881402: 'Stewart', 55517692: 'Richland WA', 234684445: 'Not provided', 182525952: 'Not provided', 509953: 'Nashville', 183355392: 'Not provided', 192452612: 'Not provided', 60100622: 'Not provided', 217464856: 'Not provided', 15446041: 'Nashville', 212512802: 'Not provided', 131098662: 'Not provided', 94914602: 'Not provided', 6209579: 'Not provided', 10604590: 'Not provided', 70666292: 'Not provided', 14307382: 'Not provided', 54437942: 'Spring Hill', 41685052: 'Smyrna', 222517314: 'Nashville', 208949319: 'Not provided', 141490252: 'Germantown', 194631761: 'Not provided', 195481687: 'Not provided', 204427351: 'Not provided', 161587302: 'Not provided', 170602602: 'Franklin', 53121132: 'Knights Landing, CA', 188504181: 'Not provided', 4169858: 'Nashville', 196309128: 'Not provided', 3795081: 'Huntingdon, TN', 111779982: 'Nashville, TN', 85557392: 'Not provided', 225593489: 'Not provided', 185870499: 'Leitchfield', 191160484: 'Not provided', 105865382: 'Not provided', 218816696: 'Not provided', 190834875: 'San Francisco', 208429247: 'Nashville', 207118547: 'Not provided', 203239640: 'Not provided', 225249498: 'Not provided', 185194718: 'Not provided', 190505207: 'Not provided', 188147962: 'Not provided', 82204922: 'Smyrna, TN', 223445245: 'Not provided', 147071232: 'Not provided', 7643395: 'Not provided', 195328266: 'Not provided', 193749271: 'Not provided', 183345433: 'Not provided', 192489759: 'Not provided', 211271973: 'Not provided', 115489062: 'Not provided', 9648429: 'New York City', 190675248: 'Not provided', 33016112: 'Not provided', 11288886: 'Brentwood', 219318584: 'Not provided', 194099532: 'Not provided', 193681740: 'Not provided', 12585301: 'Not provided', 204544342: 'Not provided', 216269148: 'Not provided', 184019319: 'Nashville', 185143689: 'Not provided', 66750862: 'Nashville', 124955032: 'Nashville', 208892319: 'Not provided', 137601442: 'Nashville', 216727980: 'Madison, MS', 183056813: 'Nashville', 215849394: 'Not provided', 225546676: 'Not provided', 198058424: 'Not provided', 206481851: 'Not provided', 85547452: 'Not provided', 182630845: 'Not provided', 188166591: 'Not provided', 214688193: 'Not provided', 14344641: 'Houston', 123279812: 'Nashville', 195150281: 'Mount Juliet', 199801302: 'Not provided', 223445463: 'Not provided', 183636449: 'Not provided', 199006708: 'Not provided', 221735433: 'Not provided', 158505502: 'Not provided', 198064675: 'Not provided', 71854632: 'Not provided', 108448302: 'Not provided', 196926001: 'Not provided', 204239424: 'Not provided', 149373512: 'Franklin', 102863442: 'Whites Creek, TN', 197724764: 'Not provided', 194187871: 'Not provided', 129133182: 'Not provided', 80388742: 'Not provided', 193874577: 'Not provided', 197913247: 'Not provided', 222968479: 'Not provided', 182532772: 'Not provided', 9917104: 'Oakland', 85437112: 'Not provided', 191222460: 'Not provided', 204237509: 'Not provided', 9448133: 'Not provided', 186743497: 'Nashville', 150950602: 'Not provided', 217160398: 'Not provided', 219620057: 'Not provided', 219620059: 'Not provided', 1164000: 'Nashville', 206600930: 'Crossville', 59351782: 'Not provided', 43463402: 'San Jose, CA', 194427633: 'Not provided', 213152508: 'Not provided', 208431873: 'Not provided', 198015745: 'Not provided', 208569099: 'Not provided', 152011532: 'Smyrna, TN', 171914012: 'Not provided', 16790301: 'Not provided', 143696682: 'Not provided', 214883118: 'Chicago', 211585840: 'Not provided', 44323642: 'Not provided', 132809532: 'Not provided', 206328636: 'Not provided', 201446209: 'Not provided', 203303747: 'Not provided', 11387717: 'Not provided', 63392582: 'Not provided', 200842069: 'Not provided', 150950742: 'Not provided', 7918427: 'Nashville', 175655772: 'Not provided', 76743532: 'Not provided', 199981939: 'Not provided', 120681332: 'Not provided', 201257844: 'Not provided', 11975545: 'San Diego, CA', 215114617: 'Not provided', 199211904: 'Not provided', 204211075: 'Not provided', 153674632: 'Not provided', 189596556: 'Not provided', 178113422: 'Not provided', 214729620: 'Not provided', 14568344: 'Not provided', 127214502: 'Not provided', 52175782: 'Not provided', 184196021: 'Not provided', 195767229: 'Not provided', 73151432: 'Not provided', 207487949: 'Not provided', 184406989: 'Not provided', 225412049: 'Not provided', 184185824: 'Nashville', 187866086: 'Not provided', 41993192: 'Grosse Pointe, MI', 185967601: 'Nashville', 37843962: 'Not provided', 4353024: 'Nashville', 220722179: 'Not provided', 185367567: 'Not provided', 203244569: 'Nashville, TN', 216550429: 'Not provided', 183381022: 'Not provided', 232311841: 'Not provided', 183430179: 'Not provided', 140225572: 'Not provided', 63282212: 'Nashville', 198128679: 'Not provided', 190557229: 'Not provided', 153168942: 'Not provided', 137180212: 'Not provided', 135113782: 'Not provided', 126960742: 'Not provided', 14486634: 'San Diego, CA', 185173098: 'Not provided', 157248622: 'Not provided', 223413360: 'Not provided', 122440832: 'Not provided', 161055882: 'Nashville', 200893593: 'Not provided', 47572122: 'Chicago', 1920154: 'Nashville', 204367008: 'Not provided', 142396592: 'Not provided', 203295931: 'Not provided', 217599165: 'Not provided', 170208462: 'Not provided', 195470542: 'Not provided', 120171732: 'Not provided', 159263962: 'Not provided', 182314202: 'Not provided', 162731242: 'Not provided', 213474544: 'Not provided', 209243381: 'Not provided', 46486792: 'Not provided', 138867992: 'Not provided', 188972315: 'Not provided', 207928612: 'Not provided', 184251699: 'Not provided', 121431352: 'Not provided', 108490052: 'Columbia, SC', 145868102: 'Not provided', 204533070: 'Franklin', 190930255: 'Nashville', 202059088: 'Not provided', 195145042: 'Not provided', 71912792: 'Nashville', 30145882: 'Not provided', 204244320: 'Not provided', 197737828: 'Not provided', 170786152: 'Not provided', 231779693: 'Not provided', 220421489: 'Not provided', 176366962: 'Not provided', 158793082: 'Not provided', 210769280: 'Not provided', 211312007: 'Not provided', 37854602: 'Not provided', 168261002: 'Not provided', 195806604: 'Not provided', 175383952: 'Not provided', 75873682: 'Not provided', 12307860: 'Chicago', 230884769: 'Not provided', 201680292: 'Not provided', 198319524: 'Not provided', 186009000: 'Not provided', 203038123: 'Not provided', 220644780: 'Not provided', 181859762: 'Nashville', 23090611: 'Nashville', 200750517: 'Not provided', 198063541: 'Not provided', 189900217: 'Not provided', 102344122: 'Not provided', 182527419: 'Not provided', 126066112: 'Nashville', 132642242: 'Lebanon, TN', 55029192: 'Augusta', 211551704: 'Palo Alto', 152077792: 'Not provided', 119664102: 'Not provided', 120303082: 'Not provided', 163597802: 'Not provided', 208987635: 'Not provided', 132603382: 'Not provided', 216466935: 'Not provided', 232611325: 'Not provided', 211596798: 'Not provided', 9358849: 'Not provided', 184268293: 'Not provided', 111701512: 'Not provided', 209223183: 'Not provided', 189558288: 'Not provided', 211531285: 'Not provided', 211551769: 'Nashville', 187817509: 'Not provided', 204439081: 'Not provided', 80711212: 'Not provided', 14044727: 'Not provided', 192542264: 'Not provided', 203818557: 'Not provided', 8226371: 'Not provided', 117370442: 'Nashville', 230811214: 'Not provided', 195018326: 'Not provided', 12346968: 'Not provided', 101490272: 'Not provided', 193185381: 'Hermitage', 7816806: 'Atlanta', 188094055: 'Not provided', 214873705: 'Not provided', 207978090: 'Nashville', 198332016: 'Not provided', 219874928: 'Not provided', 132402812: 'Not provided', 214759042: 'Not provided', 8273538: 'Nashville', 11804293: 'Not provided', 204412550: 'Not provided', 35399302: 'Des Moines, IA', 233590417: 'Not provided', 198016657: 'Not provided', 182072982: 'Nashville', 13772465: 'Not provided', 216856245: 'Not provided', 204891834: 'Not provided', 189068987: 'Brentwood', 182372032: 'Not provided', 194746048: 'Not provided', 217290442: 'Not provided', 13606604: 'Nashville', 184547023: 'Not provided', 197981907: 'Not provided', 215910105: 'Not provided', 184389351: 'Not provided', 168486642: 'Not provided', 87420672: 'Not provided', 8820481: 'Spring Hill, TN', 119047942: 'Not provided', 7534345: 'Louisville, KY', 193013525: 'Not provided', 5216038: 'Hendersonville', 185364265: 'Not provided', 7460656: 'Not provided', 195485488: 'Not provided', 211844922: 'Not provided', 224978753: 'Not provided', 218142535: 'Nashville, TN', 71851852: 'Not provided', 216962893: 'Not provided', 216364877: 'Not provided', 195329871: 'Not provided', 152606552: 'Not provided', 197424987: 'Antioch', 117434212: 'Not provided', 156522342: 'Nashville', 220624758: 'Not provided', 118556542: 'Not provided', 200421248: 'Not provided', 185194375: 'Nashville', 83117962: 'Nashville', 59013012: 'Not provided', 183103381: 'Birmingham', 38852502: 'Nashville', 223258519: 'Not provided', 187439000: 'Not provided', 222519202: 'Not provided', 11581354: 'Not provided', 198109099: 'Not provided', 96827312: 'Not provided', 9162674: 'Not provided', 182626228: 'Not provided', 207198134: 'Not provided', 191272888: 'Not provided', 145088452: 'Not provided', 172429262: 'Not provided', 129003472: 'Not provided', 222402513: 'Not provided', 215685076: 'Not provided', 129810402: 'Not provided', 116842472: 'Not provided', 40845292: 'nashville', 207185905: 'Not provided', 190398453: 'Not provided', 187353081: 'Not provided', 181669882: 'Not provided', 200114206: 'Not provided', 3949436: 'Santiago', 9137040: 'Chicago', 174311572: 'japan ', 204115611: 'Not provided', 13172898: 'Not provided', 154401702: 'Not provided', 197867050: 'Not p

In [58]:
# Check the first few nodes' attributes
for node, attrs in list(G_m.nodes(data=True))[:3]:
    print(node, attrs)

198737924 {'hometown': 'Not provided', 'city': 'Nashville', 'state': 'TN', 'lat': 36.17, 'lon': -86.78}
220654721 {'hometown': 'Not provided', 'city': 'Nashville', 'state': 'TN', 'lat': 36.16, 'lon': -86.78}
208201738 {'hometown': 'Not provided', 'city': 'Nashville', 'state': 'TN', 'lat': 36.17, 'lon': -86.72}

In [59]:
# PyG has a function to convert nx graphs into Data objects 
data = from_networkx(G_m, group_node_attrs='all')

# Can't convert the strings to Data objects and can't One-Hot Encode the strings given memory issues

#print(data.x)
#print(data.edge_index)

AttributeError: 'list' object has no attribute 'dim'

### Building Graph 2: Groups

In [53]:
groups_df

     group_id  num_members  category_id  organizer_id
0      339011        15838           23       4353803
1    19728145         1778            5     118484462
2     6335372         2869           32     108448302
3    10016242         1975           34       8111102
4    21174496         2782           31     184580248
..        ...          ...          ...           ...
597  23742545          139            9     226783032
598  20647425           97           21     173945092
599  22504351           32           32       6141229
600  21686664          118           34     126066112
601  19494897           40           33     186028004

[602 rows x 4 columns]

In [45]:
# Create dictionary of dictionaries
groups_dict = groups_df.to_dict(orient='index')

In [52]:
groups_dict

{0: {'group_id': 339011,
  'num_members': 15838,
  'category_id': 23,
  'organizer_id': 4353803},
 1: {'group_id': 19728145,
  'num_members': 1778,
  'category_id': 5,
  'organizer_id': 118484462},
 2: {'group_id': 6335372,
  'num_members': 2869,
  'category_id': 32,
  'organizer_id': 108448302},
 3: {'group_id': 10016242,
  'num_members': 1975,
  'category_id': 34,
  'organizer_id': 8111102},
 4: {'group_id': 21174496,
  'num_members': 2782,
  'category_id': 31,
  'organizer_id': 184580248},
 5: {'group_id': 11077852,
  'num_members': 918,
  'category_id': 28,
  'organizer_id': 4765912},
 6: {'group_id': 22197221,
  'num_members': 1812,
  'category_id': 23,
  'organizer_id': 199336381},
 7: {'group_id': 1585196,
  'num_members': 4828,
  'category_id': 23,
  'organizer_id': 13537265},
 8: {'group_id': 526316,
  'num_members': 3472,
  'category_id': 5,
  'organizer_id': 12229328},
 9: {'group_id': 1763190,
  'num_members': 1563,
  'category_id': 32,
  'organizer_id': 9890725},
 10: {'group_id': 18243826,
  'num_members': 2583,
  'category_id': 30,
  'organizer_id': 198309808},
 11: {'group_id': 11625832,
  'num_members': 1442,
  'category_id': 34,
  'organizer_id': 215201845},
 12: {'group_id': 168014,
  'num_members': 3286,
  'category_id': 36,
  'organizer_id': 1281684},
 13: {'group_id': 19218850,
  'num_members': 764,
  'category_id': 34,
  'organizer_id': 12825115},
 14: {'group_id': 1526075,
  'num_members': 2730,
  'category_id': 11,
  'organizer_id': 10764011},
 15: {'group_id': 1102353,
  'num_members': 3861,
  'category_id': 23,
  'organizer_id': 7528310},
 16: {'group_id': 18955830,
  'num_members': 5008,
  'category_id': 31,
  'organizer_id': 13814459},
 17: {'group_id': 18495240,
  'num_members': 1576,
  'category_id': 23,
  'organizer_id': 183268581},
 18: {'group_id': 18562307,
  'num_members': 3210,
  'category_id': 2,
  'organizer_id': 8736052},
 19: {'group_id': 18589616,
  'num_members': 862,
  'category_id': 34,
  'organizer_id': 126249582},
 20: {'group_id': 18297014,
  'num_members': 1683,
  'category_id': 23,
  'organizer_id': 183268581},
 21: {'group_id': 47094,
  'num_members': 2375,
  'category_id': 11,
  'organizer_id': 185299351},
 22: {'group_id': 20181560,
  'num_members': 1241,
  'category_id': 26,
  'organizer_id': 365419},
 23: {'group_id': 19277993,
  'num_members': 502,
  'category_id': 34,
  'organizer_id': 183378188},
 24: {'group_id': 7836842,
  'num_members': 1318,
  'category_id': 34,
  'organizer_id': 21627131},
 25: {'group_id': 18616278,
  'num_members': 629,
  'category_id': 34,
  'organizer_id': 170855672},
 26: {'group_id': 16477792,
  'num_members': 1371,
  'category_id': 34,
  'organizer_id': 16790301},
 27: {'group_id': 24803205,
  'num_members': 415,
  'category_id': 21,
  'organizer_id': 92479482},
 28: {'group_id': 14546632,
  'num_members': 451,
  'category_id': 34,
  'organizer_id': 132473852},
 29: {'group_id': 1371991,
  'num_members': 2032,
  'category_id': 10,
  'organizer_id': 13677114},
 30: {'group_id': 16062152,
  'num_members': 1026,
  'category_id': 34,
  'organizer_id': 158936252},
 31: {'group_id': 15297782,
  'num_members': 560,
  'category_id': 34,
  'organizer_id': 86371752},
 32: {'group_id': 4126912,
  'num_members': 1532,
  'category_id': 2,
  'organizer_id': 44942272},
 33: {'group_id': 20807142,
  'num_members': 1388,
  'category_id': 31,
  'organizer_id': 7377000},
 34: {'group_id': 2542802,
  'num_members': 645,
  'category_id': 32,
  'organizer_id': 26285162},
 35: {'group_id': 19266390,
  'num_members': 1444,
  'category_id': 2,
  'organizer_id': 11759637},
 36: {'group_id': 1187715,
  'num_members': 1889,
  'category_id': 10,
  'organizer_id': 4230486},
 37: {'group_id': 19997487,
  'num_members': 576,
  'category_id': 34,
  'organizer_id': 82204922},
 38: {'group_id': 3173762,
  'num_members': 1041,
  'category_id': 34,
  'organizer_id': 40336202},
 39: {'group_id': 16487812,
  'num_members': 1763,
  'category_id': 34,
  'organizer_id': 58983922},
 40: {'group_id': 6707902,
  'num_members': 1046,
  'category_id': 34,
  'organizer_id': 14589429},
 41: {'group_id': 6629622,
  'num_members': 435,
  'category_id': 31,
  'organizer_id': 12258718},
 42: {'group_id': 3047512,
  'num_members': 2058,
  'category_id': 23,
  'organizer_id': 34240622},
 43: {'group_id': 8771812,
  'num_members': 651,
  'category_id': 34,
  'organizer_id': 4353024},
 44: {'group_id': 9376702,
  'num_members': 1091,
  'category_id': 34,
  'organizer_id': 7918427},
 45: {'group_id': 1360698,
  'num_members': 1118,
  'category_id': 34,
  'organizer_id': 1813015},
 46: {'group_id': 19030621,
  'num_members': 567,
  'category_id': 12,
  'organizer_id': 7859383},
 47: {'group_id': 929402,
  'num_members': 6331,
  'category_id': 23,
  'organizer_id': 8939765},
 48: {'group_id': 1324203,
  'num_members': 2360,
  'category_id': 22,
  'organizer_id': 19801731},
 49: {'group_id': 4705492,
  'num_members': 2307,
  'category_id': 2,
  'organizer_id': 26706942},
 50: {'group_id': 22817838,
  'num_members': 434,
  'category_id': 34,
  'organizer_id': 7534345},
 51: {'group_id': 1179719,
  'num_members': 965,
  'category_id': 13,
  'organizer_id': 9770948},
 52: {'group_id': 19556549,
  'num_members': 1103,
  'category_id': 14,
  'organizer_id': 184777575},
 53: {'group_id': 5618532,
  'num_members': 501,
  'category_id': 34,
  'organizer_id': 204135137},
 54: {'group_id': 25481468,
  'num_members': 113,
  'category_id': 23,
  'organizer_id': 87574402},
 55: {'group_id': 1776274,
  'num_members': 1649,
  'category_id': 2,
  'organizer_id': 10119159},
 56: {'group_id': 1728035,
  'num_members': 1643,
  'category_id': 34,
  'organizer_id': 72560962},
 57: {'group_id': 15552112,
  'num_members': 652,
  'category_id': 6,
  'organizer_id': 146326152},
 58: {'group_id': 18314164,
  'num_members': 784,
  'category_id': 34,
  'organizer_id': 183427754},
 59: {'group_id': 227528,
  'num_members': 1417,
  'category_id': 16,
  'organizer_id': 2434993},
 60: {'group_id': 26076650,
  'num_members': 55,
  'category_id': 34,
  'organizer_id': 35147542},
 61: {'group_id': 16447162,
  'num_members': 391,
  'category_id': 34,
  'organizer_id': 8111102},
 62: {'group_id': 535553,
  'num_members': 881,
  'category_id': 34,
  'organizer_id': 14344641},
 63: {'group_id': 1358081,
  'num_members': 1447,
  'category_id': 2,
  'organizer_id': 44942272},
 64: {'group_id': 18476981,
  'num_members': 2514,
  'category_id': 1,
  'organizer_id': 40582582},
 65: {'group_id': 18361585,
  'num_members': 1684,
  'category_id': 34,
  'organizer_id': 5900662},
 66: {'group_id': 5282132,
  'num_members': 1191,
  'category_id': 22,
  'organizer_id': 65541132},
 67: {'group_id': 24906881,
  'num_members': 97,
  'category_id': 34,
  'organizer_id': 22476571},
 68: {'group_id': 1492619,
  'num_members': 2163,
  'category_id': 2,
  'organizer_id': 15369081},
 69: {'group_id': 18414590,
  'num_members': 690,
  'category_id': 2,
  'organizer_id': 187452711},
 70: {'group_id': 541319,
  'num_members': 2644,
  'category_id': 21,
  'organizer_id': 2984170},
 71: {'group_id': 1349592,
  'num_members': 2261,
  'category_id': 11,
  'organizer_id': 7563113},
 72: {'group_id': 16954142,
  'num_members': 1084,
  'category_id': 2,
  'organizer_id': 13020262},
 73: {'group_id': 21837219,
  'num_members': 302,
  'category_id': 34,
  'organizer_id': 129133182},
 74: {'group_id': 23053409,
  'num_members': 296,
  'category_id': 12,
  'organizer_id': 11498435},
 75: {'group_id': 1431882,
  'num_members': 1328,
  'category_id': 23,
  'organizer_id': 9101358},
 76: {'group_id': 24693747,
  'num_members': 114,
  'category_id': 13,
  'organizer_id': 16881781},
 77: {'group_id': 18314669,
  'num_members': 445,
  'category_id': 28,
  'organizer_id': 2201276},
 78: {'group_id': 25884191,
  'num_members': 143,
  'category_id': 14,
  'organizer_id': 6440691},
 79: {'group_id': 10000962,
  'num_members': 72,
  'category_id': 1,
  'organizer_id': 108686552},
 80: {'group_id': 22736876,
  'num_members': 126,
  'category_id': 2,
  'organizer_id': 191532521},
 81: {'group_id': 1751502,
  'num_members': 959,
  'category_id': 2,
  'organizer_id': 9919399},
 82: {'group_id': 19443174,
  'num_members': 398,
  'category_id': 31,
  'organizer_id': 68682832},
 83: {'group_id': 18850080,
  'num_members': 438,
  'category_id': 34,
  'organizer_id': 10083866},
 84: {'group_id': 23674770,
  'num_members': 250,
  'category_id': 14,
  'organizer_id': 4579315},
 85: {'group_id': 18529135,
  'num_members': 360,
  'category_id': 2,
  'organizer_id': 34583172},
 86: {'group_id': 19822479,
  'num_members': 1192,
  'category_id': 2,
  'organizer_id': 201177047},
 87: {'group_id': 26000035,
  'num_members': 223,
  'category_id': 1,
  'organizer_id': 12143808},
 88: {'group_id': 17467312,
  'num_members': 646,
  'category_id': 34,
  'organizer_id': 54437942},
 89: {'group_id': 19292162,
  'num_members': 237,
  'category_id': 34,
  'organizer_id': 145632652},
 90: {'group_id': 2556962,
  'num_members': 1055,
  'category_id': 3,
  'organizer_id': 11578777},
 91: {'group_id': 1274150,
  'num_members': 1187,
  'category_id': 22,
  'organizer_id': 9726350},
 92: {'group_id': 25641512,
  'num_members': 91,
  'category_id': 23,
  'organizer_id': 12258718},
 93: {'group_id': 18425641,
  'num_members': 510,
  'category_id': 2,
  'organizer_id': 83214022},
 94: {'group_id': 22585660,
  'num_members': 1035,
  'category_id': 31,
  'organizer_id': 194923584},
 95: {'group_id': 204767,
  'num_members': 292,
  'category_id': 34,
  'organizer_id': 119792682},
 96: {'group_id': 25521445,
  'num_members': 104,
  'category_id': 34,
  'organizer_id': 225659788},
 97: {'group_id': 2520612,
  'num_members': 1770,
  'category_id': 18,
  'organizer_id': 6721449},
 98: {'group_id': 5882552,
  'num_members': 1422,
  'category_id': 6,
  'organizer_id': 59643462},
 99: {'group_id': 1498076,
  'num_members': 887,
  'category_id': 2,
  'organizer_id': 9470306},
 100: {'group_id': 19847832,
  'num_members': 341,
  'category_id': 32,
  'organizer_id': 81052872},
 101: {'group_id': 26069557,
  'num_members': 42,
  'category_id': 34,
  'organizer_id': 202311485},
 102: {'group_id': 6641192,
  'num_members': 874,
  'category_id': 14,
  'organizer_id': 16624181},
 103: {'group_id': 20384452,
  'num_members': 105,
  'category_id': 18,
  'organizer_id': 90086912},
 104: {'group_id': 1622500,
  'num_members': 799,
  'category_id': 2,
  'organizer_id': 12131688},
 105: {'group_id': 24584525,
  'num_members': 591,
  'category_id': 23,
  'organizer_id': 48990822},
 106: {'group_id': 10426762,
  'num_members': 401,
  'category_id': 2,
  'organizer_id': 61683832},
 107: {'group_id': 24039540,
  'num_members': 188,
  'category_id': 11,
  'organizer_id': 169396342},
 108: {'group_id': 20806988,
  'num_members': 318,
  'category_id': 27,
  'organizer_id': 183534666},
 109: {'group_id': 22023226,
  'num_members': 328,
  'category_id': 2,
  'organizer_id': 184259142},
 110: {'group_id': 18855476,
  'num_members': 243,
  'category_id': 34,
  'organizer_id': 197929760},
 111: {'group_id': 20269464,
  'num_members': 90,
  'category_id': 32,
  'organizer_id': 199853583},
 112: {'group_id': 11131552,
  'num_members': 3381,
  'category_id': 23,
  'organizer_id': 92743262},
 113: {'group_id': 24125934,
  'num_members': 43,
  'category_id': 34,
  'organizer_id': 178742432},
 114: {'group_id': 22130047,
  'num_members': 285,
  'category_id': 22,
  'organizer_id': 70636672},
 115: {'group_id': 20336043,
  'num_members': 1639,
  'category_id': 31,
  'organizer_id': 12347749},
 116: {'group_id': 18506072,
  'num_members': 3811,
  'category_id': 31,
  'organizer_id': 188857906},
 117: {'group_id': 710272,
  'num_members': 1382,
  'category_id': 22,
  'organizer_id': 2652159},
 118: {'group_id': 6190702,
  'num_members': 2050,
  'category_id': 31,
  'organizer_id': 34240622},
 119: {'group_id': 10178242,
  'num_members': 1166,
  'category_id': 34,
  'organizer_id': 110489102},
 120: {'group_id': 19828398,
  'num_members': 436,
  'category_id': 16,
  'organizer_id': 27465332},
 121: {'group_id': 1507431,
  'num_members': 427,
  'category_id': 11,
  'organizer_id': 10198845},
 122: {'group_id': 252576,
  'num_members': 1035,
  'category_id': 2,
  'organizer_id': 12011595},
 123: {'group_id': 11776502,
  'num_members': 610,
  'category_id': 22,
  'organizer_id': 6780662},
 124: {'group_id': 19416348,
  'num_members': 298,
  'category_id': 2,
  'organizer_id': 83272622},
 125: {'group_id': 19528743,
  'num_members': 441,
  'category_id': 2,
  'organizer_id': 144256692},
 126: {'group_id': 18494105,
  'num_members': 1491,
  'category_id': 34,
  'organizer_id': 104388972},
 127: {'group_id': 25810092,
  'num_members': 35,
  'category_id': 16,
  'organizer_id': 80142302},
 128: {'group_id': 22374557,
  'num_members': 289,
  'category_id': 16,
  'organizer_id': 38395162},
 129: {'group_id': 23723436,
  'num_members': 87,
  'category_id': 31,
  'organizer_id': 226769794},
 130: {'group_id': 13560402,
  'num_members': 540,
  'category_id': 34,
  'organizer_id': 120578592},
 131: {'group_id': 25448937,
  'num_members': 284,
  'category_id': 1,
  'organizer_id': 107126142},
 132: {'group_id': 7700282,
  'num_members': 1292,
  'category_id': 2,
  'organizer_id': 85602482},
 133: {'group_id': 6230672,
  'num_members': 493,
  'category_id': 31,
  'organizer_id': 1720391},
 134: {'group_id': 1457232,
  'num_members': 2921,
  'category_id': 4,
  'organizer_id': 34423222},
 135: {'group_id': 12847372,
  'num_members': 802,
  'category_id': 23,
  'organizer_id': 80583062},
 136: {'group_id': 1307837,
  'num_members': 520,
  'category_id': 15,
  'organizer_id': 4163995},
 137: {'group_id': 23394559,
  'num_members': 50,
  'category_id': 11,
  'organizer_id': 184600207},
 138: {'group_id': 20135961,
  'num_members': 1124,
  'category_id': 31,
  'organizer_id': 198403977},
 139: {'group_id': 20065975,
  'num_members': 187,
  'category_id': 11,
  'organizer_id': 204653383},
 140: {'group_id': 22132964,
  'num_members': 49,
  'category_id': 31,
  'organizer_id': 10169306},
 141: {'group_id': 24743042,
  'num_members': 414,
  'category_id': 31,
  'organizer_id': 227859656},
 142: {'group_id': 1169709,
  'num_members': 1189,
  'category_id': 20,
  'organizer_id': 182568739},
 143: {'group_id': 1581956,
  'num_members': 52,
  'category_id': 16,
  'organizer_id': 14000160},
 144: {'group_id': 1417288,
  'num_members': 2060,
  'category_id': 21,
  'organizer_id': 1966421},
 145: {'group_id': 11184352,
  'num_members': 322,
  'category_id': 2,
  'organizer_id': 124644362},
 146: {'group_id': 26091301,
  'num_members': 43,
  'category_id': 28,
  'organizer_id': 232528811},
 147: {'group_id': 18837102,
  'num_members': 166,
  'category_id': 34,
  'organizer_id': 100449852},
 148: {'group_id': 26090658,
  'num_members': 20,
  'category_id': 2,
  'organizer_id': 13385553},
 149: {'group_id': 20583464,
  'num_members': 234,
  'category_id': 22,
  'organizer_id': 5212354},
 150: {'group_id': 18549438,
  'num_members': 1769,
  'category_id': 30,
  'organizer_id': 77649082},
 151: {'group_id': 25681644,
  'num_members': 52,
  'category_id': 32,
  'organizer_id': 212106559},
 152: {'group_id': 1772099,
  'num_members': 1763,
  'category_id': 21,
  'organizer_id': 5129031},
 153: {'group_id': 18801828,
  'num_members': 727,
  'category_id': 2,
  'organizer_id': 128146292},
 154: {'group_id': 7151442,
  'num_members': 372,
  'category_id': 34,
  'organizer_id': 70666292},
 155: {'group_id': 7130232,
  'num_members': 1308,
  'category_id': 34,
  'organizer_id': 14344641},
 156: {'group_id': 12588802,
  'num_members': 91,
  'category_id': 22,
  'organizer_id': 4817345},
 157: {'group_id': 3376042,
  'num_members': 605,
  'category_id': 2,
  'organizer_id': 9470306},
 158: {'group_id': 788001,
  'num_members': 992,
  'category_id': 14,
  'organizer_id': 6780662},
 159: {'group_id': 19654655,
  'num_members': 516,
  'category_id': 34,
  'organizer_id': 194047958},
 160: {'group_id': 7699922,
  'num_members': 195,
  'category_id': 28,
  'organizer_id': 4720318},
 161: {'group_id': 405938,
  'num_members': 525,
  'category_id': 34,
  'organizer_id': 3246917},
 162: {'group_id': 25648018,
  'num_members': 314,
  'category_id': 31,
  'organizer_id': 197966717},
 163: {'group_id': 23573879,
  'num_members': 423,
  'category_id': 27,
  'organizer_id': 196315467},
 164: {'group_id': 25441371,
  'num_members': 236,
  'category_id': 14,
  'organizer_id': 190717209},
 165: {'group_id': 24850344,
  'num_members': 237,
  'category_id': 22,
  'organizer_id': 192829365},
 166: {'group_id': 25076888,
  'num_members': 64,
  'category_id': 34,
  'organizer_id': 13490762},
 167: {'group_id': 23594916,
  'num_members': 198,
  'category_id': 34,
  'organizer_id': 96331022},
 168: {'group_id': 18714758,
  'num_members': 2634,
  'category_id': 31,
  'organizer_id': 77649082},
 169: {'group_id': 26040985,
  'num_members': 36,
  'category_id': 16,
  'organizer_id': 201787805},
 170: {'group_id': 19904711,
  'num_members': 107,
  'category_id': 34,
  'organizer_id': 86263532},
 171: {'group_id': 25681787,
  'num_members': 67,
  'category_id': 22,
  'organizer_id': 7325785},
 172: {'group_id': 1741429,
  'num_members': 491,
  'category_id': 2,
  'organizer_id': 228396306},
 173: {'group_id': 14649032,
  'num_members': 516,
  'category_id': 34,
  'organizer_id': 9590115},
 174: {'group_id': 20186791,
  'num_members': 2189,
  'category_id': 31,
  'organizer_id': 209069325},
 175: {'group_id': 20166757,
  'num_members': 281,
  'category_id': 6,
  'organizer_id': 208732641},
 176: {'group_id': 18629337,
  'num_members': 109,
  'category_id': 32,
  'organizer_id': 184367689},
 177: {'group_id': 18823274,
  'num_members': 144,
  'category_id': 14,
  'organizer_id': 221829385},
 178: {'group_id': 21989057,
  'num_members': 83,
  'category_id': 34,
  'organizer_id': 207103295},
 179: {'group_id': 21957723,
  'num_members': 181,
  'category_id': 2,
  'organizer_id': 220077960},
 180: {'group_id': 25397992,
  'num_members': 73,
  'category_id': 22,
  'organizer_id': 61526062},
 181: {'group_id': 20493986,
  'num_members': 210,
  'category_id': 2,
  'organizer_id': 213434886},
 182: {'group_id': 20402980,
  'num_members': 124,
  'category_id': 11,
  'organizer_id': 212154798},
 183: {'group_id': 25326528,
  'num_members': 47,
  'category_id': 32,
  'organizer_id': 230674257},
 184: {'group_id': 19934054,
  'num_members': 205,
  'category_id': 9,
  'organizer_id': 200686755},
 185: {'group_id': 8805172,
  'num_members': 499,
  'category_id': 26,
  'organizer_id': 12983193},
 186: {'group_id': 19049542,
  'num_members': 865,
  'category_id': 21,
  'organizer_id': 193696306},
 187: {'group_id': 16140462,
  'num_members': 200,
  'category_id': 12,
  'organizer_id': 8809394},
 188: {'group_id': 1451826,
  'num_members': 726,
  'category_id': 6,
  'organizer_id': 70762772},
 189: {'group_id': 15335602,
  'num_members': 315,
  'category_id': 16,
  'organizer_id': 153513242},
 190: {'group_id': 2496252,
  'num_members': 874,
  'category_id': 22,
  'organizer_id': 25507792},
 191: {'group_id': 19064659,
  'num_members': 50,
  'category_id': 6,
  'organizer_id': 56725922},
 192: {'group_id': 25471951,
  'num_members': 53,
  'category_id': 11,
  'organizer_id': 31995212},
 193: {'group_id': 20836828,
  'num_members': 35,
  'category_id': 18,
  'organizer_id': 133440072},
 194: {'group_id': 20241153,
  'num_members': 47,
  'category_id': 33,
  'organizer_id': 208888939},
 195: {'group_id': 20129636,
  'num_members': 112,
  'category_id': 18,
  'organizer_id': 183590843},
 196: {'group_id': 25115699,
  'num_members': 19,
  'category_id': 4,
  'organizer_id': 220443481},
 197: {'group_id': 22873954,
  'num_members': 171,
  'category_id': 9,
  'organizer_id': 223501599},
 198: {'group_id': 21747934,
  'num_members': 274,
  'category_id': 12,
  'organizer_id': 217710404},
 199: {'group_id': 19687074,
  'num_members': 703,

In [46]:
# Build graph
G_g = nx.from_pandas_edgelist(
    subset,
    source='member1',
    target='member2',
    edge_attr='weight',
    create_using=nx.Graph())
# Set attributes 
nx.set_node_attributes(G_g, groups_dict)

In [50]:
print(nx.get_node_attributes(G_g, 'group_id'))

{}

In [47]:
G_g

In [ ]:
# PyG has a function to convert nx graphs into Data objects 
data = from_networkx(G_g, group_node_attrs='')
print(data.x)
print(data.edge_index)

RuntimeError: torch.cat(): expected a non-empty list of Tensors